# Generated by Django 4.1.7 on 2023-04-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('mediosInternos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Nombre doctor')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediosInternos.especialidad', verbose_name='Especialidad')),
            ],
        ),
    ]
