# Generated by Django 4.1.7 on 2023-03-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediosInternos', '0002_alter_cita_cliente_alter_cita_doctor_and_more'),
        ('core', '0002_alter_cliente_activo_alter_cliente_apellido_and_more'),
        ('docEspecializado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorespecialista',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Nombre doctor'),
        ),
        migrations.AlterField(
            model_name='doctorespecialista',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediosInternos.especialidad', verbose_name='Especialidad'),
        ),
    ]
