# Generated by Django 4.1.7 on 2023-03-29 15:50

import Apps.mediosInternos.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_activo_alter_cliente_apellido_and_more'),
        ('mediosInternos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Nombre cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Nombre doctor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=Apps.mediosInternos.models.Duracion(default=datetime.timedelta(0), help_text='Duración en formato hh:mm:ss'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
