# Generated by Django 4.1.7 on 2023-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=58, verbose_name='Numero documento')),
                ('nombre', models.CharField(max_length=48, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=48, verbose_name='Apellido')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=16, verbose_name='Telefono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipoUsuario', models.CharField(default='Cliente', max_length=10, verbose_name='Tipo usuario')),
                ('activo', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=58, verbose_name='Numero documento')),
                ('nombre', models.CharField(max_length=48, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=48, verbose_name='Apellido')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=16, verbose_name='Telefono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipoUsuario', models.CharField(default='Doctor', max_length=10, verbose_name='Tipo usuario')),
                ('disponible', models.BooleanField(verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=58, verbose_name='Numero documento')),
                ('nombre', models.CharField(max_length=48, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=48, verbose_name='Apellido')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=16, verbose_name='Telefono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipoUsuario', models.CharField(default='Enfermero', max_length=10, verbose_name='Tipo usuario')),
                ('activo', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Enfermero',
                'verbose_name_plural': 'Enfermeros',
                'ordering': ['-created'],
            },
        ),
    ]
