# Generated by Django 4.1.7 on 2023-03-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=48, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=48, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeroDocumento',
            field=models.CharField(max_length=58, verbose_name='Numero documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=16, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoUsuario',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=10, verbose_name='Tipo usuario'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='apellido',
            field=models.CharField(max_length=48, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='disponible',
            field=models.BooleanField(verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(max_length=48, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='numeroDocumento',
            field=models.CharField(max_length=58, verbose_name='Numero documento'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(max_length=16, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tipoUsuario',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=10, verbose_name='Tipo usuario'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='activo',
            field=models.BooleanField(verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='apellido',
            field=models.CharField(max_length=48, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='nombre',
            field=models.CharField(max_length=48, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='numeroDocumento',
            field=models.CharField(max_length=58, verbose_name='Numero documento'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='telefono',
            field=models.CharField(max_length=16, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='tipoUsuario',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=10, verbose_name='Tipo usuario'),
        ),
    ]
