# Generated by Django 4.1.7 on 2023-03-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorespecialista',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorespecialista',
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='DoctorEspecialista',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
