# Generated by Django 4.1.7 on 2023-03-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_doctorespecialista_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoUsuario',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tipoUsuario',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='tipoUsuario',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=10),
        ),
    ]
